# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  USERNAME: $(Username)
  PASSWORD: $(Password)

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: DownloadSecureFile@1
    name: pluginkey
    inputs:
      secureFile: 'pluginkey.key'
  - task: CmdLine@2
    name: bundlescript
    inputs:
      script: './bundle-plugin.py -u $(USERNAME) -p $(PASSWORD) -i $(Instance) -k $(pluginkey.secureFilePath)'